# EnderUtils by Ferlux
# Arquivo de configuração

AlwaysDay:
  enable: true
  worlds:
    - 'Mundo'

## PLACEHOLDERS: <players> <center>
JoinMessage:
  # Mensagem para todos quando o jogador entrar pela primeira vez
  enableFirstMessage: true
  messageFirst: "&6Seja bem-vindo(a) &e<player> &6pela primeira vez no servidor!"
  # Mensagem enviada ao jogador toda vez ao entrar
  enable: true
  message:
    - ""
    - "<center>&#9a1ffb&lE&#af23fc&ln&#c327fc&ld&#d82bfd&le&#ec2ffd&lr&f&lCraft"
    - "<center>&7Seja bem-vindo ao &nservidor&7."
    - ""
    - " &#FDF300&l➜ &7No momento temos &#FDF300<players> jogadores &7online."
    - " &#FDF300&l➜ &7Use &#FDF300/discord &7para vincular sua conta ao Discord."
    - " &#FDF300&l➜ &7Use &#FDF300/2fa email &7para adicionar um email de recuperação."
    - "<center>&#fb00f1&lD&#fb18d9&li&#fb31c1&lv&#fc49a9&li&#fc6191&lr&#fc7a79&lt&#fc9260&la&#fcaa48&l-&#fdc230&ls&#fddb18&le&#fdf300&l!"
    - ""

Protector:
  # bypass permission: enderutils.protector.bypass.*
  enable: true
  # enable-disable block of hidden syntax (commands with :) on chat and tab complete. example: /minecraft:give - bypass permission: enderutils.protector.bypass.hiddenSyntax
  blockHiddenSyntax: true
  errorMessage: '&c&lERRO ➜ &fComando não encontrado.'
  # block commands below for everyone - bypass permission: enderutils.protector.bypass.cmds (bypass all commands)
  # to make command visible for just some players, use ;<group-name> in the end of the command (example: pl;admin)
  # so players with permission enderutils.protector.group.admin will can see and use this command
  # these commands will be hidden from tab complete and blockeds from execution, unless player has bypass permission
  blockedCommands:
    - 'pl'
    - 'plugins'
    - 'ver'
    - 'aegis'
    - 'anticrash'
    - 'antibot'
    - 'actionbar'
    - 'alert'
    - 'alerta'
    - 'anticrasher'
    - 'astools'
    - 'antiexploit'
    - 'ast'
    - 'ascmd'
    - 'crash'
    - 'crasher'
    - 'version'
    - 'about'
    - 'bukkit'
    - 'icanhasbukkit'
    - 'help'
    - 'me'
    - 'spark'
    - 'sound'
    - 'region'
    - 'regions'
    - 'about'
    - 'worldedit'
    - 'we'
    - 'w'
    - 'decentholograms'
    - 'luckperms'
    - 'fawe'
    - 'fastasyncworldedit'
    - 'splugins'
    - 'stormpls'
    - 'stormplugins'
    - 'stormplugins:sp'
    - 'sp'
    - 'activatevip'
    - 'ativartransacao'
    - 'ativarvip'
    - 'changevip'
    - 'chavedar'
    - 'chaveenviar'
    - 'congelartempovip'
    - 'congelarvip'
    - 'congelarvips'
    - 'convert'
    - 'converter'
    - 'darchave'
    - 'darvip'
    - 'deletarchave'
    - 'deletarkey'
    - 'deletekey'
    - 'editarchave'
    - 'editarkey'
    - 'editchave'
    - 'editkey'
    - 'enviarchave'
    - 'freezetimevip'
    - 'freezevip'
    - 'freezevips'
    - 'freezeviptime'
    - 'generatekey'
    - 'gerarchave'
    - 'gerarkey'
    - 'givevip'
    - 'keysend'
    - 'newkey'
    - 'removekey'
    - 'removerchave'
    - 'removerkey'
    - 'removevip'
    - 'sendkey'
    - 'setvip'
    - 'tirarvip'
    - 'transacao'
    - 'vipcongelar'
    - 'vipcongelartempo'
    - 'vipfreeze'
    - 'vipscongelar'
    - 'vipsfreeze'
    - 'avisar;mod'
    - 'aviso;mod'
    - 'avisos;mod'
    - 'ban;mod'
    - 'ban-ip;mod'
    - 'ban-temp;mod'
    - 'banip;mod'
    - 'banip-temp;mod'
    - 'banir;mod'
    - 'banir-ip;mod'
    - 'banirip;mod'
    - 'bantemp;mod'
    - 'bantempip;mod'
    - 'denuncia;mod'
    - 'denunciar;mod'
    - 'denuncias;mod'
    - 'despunir;mod'
    - 'expulsar;mod'
    - 'historic'
    - 'historico'
    - 'historicos'
    - 'kick'
    - 'kickar'
    - 'mutar'
    - 'mute'
    - 'mute-temp'
    - 'mutetemp'
    - 'punicoes'
    - 'punir'
    - 'punish'
    - 'punishes'
    - 'report'
    - 'reportar'
    - 'reportlist'
    - 'reports'
    - 'temp-ban'
    - 'temp-ban-ip'
    - 'temp-banip'
    - 'temp-mute'
    - 'tempban'
    - 'tempban-ip'
    - 'tempbanip'
    - 'tempbanir-ip'
    - 'tempbanirip'
    - 'tempmute'
    - 'unban'
    - 'unmute'
    - 'unpunish'
    - 'warn'