# EnderUtils by Ferlux
# Arquivo de configuração

AlwaysDay:
  enable: true
  worlds:
    - 'Mundo'

## PLACEHOLDERS: <players> <center>
JoinMessage:
  # Mensagem para todos quando o jogador entrar pela primeira vez
  enableFirstMessage: true
  messageFirst: "&6Seja bem-vindo(a) &e<player> &6pela primeira vez no servidor!"
  # Mensagem enviada ao jogador toda vez ao entrar
  enable: true
  message:
    - ""
    - "<center>&#9a1ffb&lE&#af23fc&ln&#c327fc&ld&#d82bfd&le&#ec2ffd&lr&f&lCraft"
    - "<center>&7Seja bem-vindo ao &nservidor&7."
    - ""
    - " &#FDF300&l➜ &7No momento temos &#FDF300<players> jogadores &7online."
    - " &#FDF300&l➜ &7Use &#FDF300/discord &7para vincular sua conta ao Discord."
    - " &#FDF300&l➜ &7Use &#FDF300/2fa email &7para adicionar um email de recuperação."
    - "<center>&#fb00f1&lD&#fb18d9&li&#fb31c1&lv&#fc49a9&li&#fc6191&lr&#fc7a79&lt&#fc9260&la&#fcaa48&l-&#fdc230&ls&#fddb18&le&#fdf300&l!"
    - ""

Protector:
  # bypass permission: enderutils.protector.bypass
  enable: true
  # enable-disable block of hidden syntax on chat and tab complete. example: /minecraft:give
  blockHiddenSyntax: true
  errorMessage: '&c&lERRO ➜ &fComando não encontrado.'
  # block commands below
  blockedCommands:
    - 'pl'
    - 'plugins'